### ISSUE TITLE
유저 버튼 클릭시 화면이 움찔거려요

### ISSUE THREAD

**Issue by kwag93** [rkskekzzz/timong#26]
유저 버튼을 클릭하기전에는 스크롤바가 있는데 버튼을 클릭하면 스크롤바가 사라지면서 계속 움찔꺼리는 느낌이 나요
개선이 가능하면 좋을꺼같아요

**Comment by rkskekzzz** [comment]
달력에 있는 날짜를 클릭한 경우를 말씀하신 건가요?
해당 경우는 디버깅에 어려움이 있어서 추후 원인이 파악되면 수정해보겠습니다 ㅜㅜ

**Comment by rkskekzzz** [comment]
fix
